AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  TerraformLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 483
      Role: >-
        SomeRoleWithTerraformAccess
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSTopic1
      Environment:
        Variables:
          TF_ACTION: apply
          TF_CLI_ARGS: '-input=false'
          TF_CLI_CONFIG_FILE: ''
          TF_IN_AUTOMATION: '1'
          TF_LOG: ERROR
          TF_PLUGIN_CACHE_DIR: /tmp/plugin-cache/
  SNSTopic1:
    Type: 'AWS::SNS::Topic'
